services:
  image: mangar/rails-pg:4.2.6
  command: bash -c "/bin/bash docker-start.sh"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres

postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"