next-webapp:
  image: mangar/webapp-front:8.2
  command: bash -c "/bin/bash docker-compose.sh"  
  volumes:
    - .:/app
  ports:
    - "3000:3000"
    - "8080:8080"
  environment:
    - NODE_ENV=development  