FROM python:2.7.9

MAINTAINER Marcio Mangar "marcio.mangar@gmail.com"


RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python-pip python-dev 
RUN pip install --upgrade pip
RUN pip install RPi.GPIO  


